branches:
    only:
        - master
        - ci
git:
    depth: 10

language: node_js

env:
    global:
        ATOM_CI_PACKAGE_ROOT: spec

node_js: 12

matrix:
    include:
        - os:   osx
          env:  ATOM_CHANNEL=stable

addons:
    apt:
        packages:
            - build-essential
            - fakeroot
            - git
            - libgconf2-4
            - libsecret-1-dev

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - node --version
    - "$PWD/stuff.sh"
