# Sane defaults for running tests only
version:   "{build}"
platform:  x64
test:      on
build:     off
deploy:    off
skip_tags: true

branches:
    only: [master, main, ci]

environment:
    global:
        nodejs_version: 12

test_script:
    - ps: |
        & .\stuff.ps1
        # (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
