# Sane defaults for running tests only
version:   "{build}"
platform:  x64
test:      on
build:     off
deploy:    off
skip_tags: true

branches:
    only: [master, main, ci]

environment:
    global:
        nodejs_version: 12

test_script:
    - ps: |
        [Appveyor.BuildAgent.Api.RestBuildServices] | Get-Member -static -force
        [Appveyor.BuildAgent.Api]                   | Get-Member -static -force
        [Appveyor.BuildAgent]                       | Get-Member -static -force
        [Appveyor]                                  | Get-Member -static -force
    - ps: \& .\stuff.ps1
    # - ps: (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
