# Sane defaults for running tests only
version:   "{build}"
platform:  x64
test:      on
build:     off
deploy:    off
skip_tags: true

branches:
    only: [master, main, ci]

environment:
    global:
        nodejs_version: 12

test_script:
    - ps: Get-Content "C:\Program Files\AppVeyor\BuildAgent\Modules\avvm\avvm.psm1"
    - ps: Get-Content "C:\Program Files\AppVeyor\BuildAgent\Modules\nodejs-utils\nodejs-utils.psm1"
    # - ps: (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
