version: 2
jobs:
    build:
        working_directory: /tmp/project
        environment:
            DISPLAY: ":99"

        docker:
        - image: circleci/node:latest

        steps:
        - checkout
        - run:
                name: Test something for a sec
                command: env | sort
