name: CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    test:
        name: Run tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node: [13.2, 14, 16, 18]

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js v${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm

            - name:  Install dependencies
              shell: sh
              run:   make -B install

            - name:  Run package tests
              shell: sh
              run:   make all && make coverage
