name: CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}-latest
        strategy:
            matrix:
                os: [Ubuntu, macOS, Windows]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install GNU on Windows
              if:   startsWith(matrix.os, 'Windows')
              run: |
                  choco install gow
                  refreshenv

            - name:  Run package tests
              shell: sh
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: |
                  echo "$DUMMY_TOKEN"
                  npm install c8 coveralls
                  npx c8 ./index.mjs

            - name: List environment variables
              shell: sh
              run: |
                  printf 'CI:                        %s\n'  '${{ env.CI }}'
                  printf 'GITHUB_ACTION:             %s\n'  '${{ env.GITHUB_ACTION }}'
                  printf 'GITHUB_ACTION_PATH:        %s\n'  '${{ env.GITHUB_ACTION_PATH }}'
                  printf 'GITHUB_ACTION_REPOSITORY:  %s\n'  '${{ env.GITHUB_ACTION_REPOSITORY }}'
                  printf 'GITHUB_ACTIONS:            %s\n'  '${{ env.GITHUB_ACTIONS }}'
                  printf 'GITHUB_ACTOR:              %s\n'  '${{ env.GITHUB_ACTOR }}'
                  printf 'GITHUB_API_URL:            %s\n'  '${{ env.GITHUB_API_URL }}'
                  printf 'GITHUB_BASE_REF:           %s\n'  '${{ env.GITHUB_BASE_REF }}'
                  printf 'GITHUB_ENV:                %s\n'  '${{ env.GITHUB_ENV }}'
                  printf 'GITHUB_EVENT_NAME:         %s\n'  '${{ env.GITHUB_EVENT_NAME }}'
                  printf 'GITHUB_EVENT_PATH:         %s\n'  '${{ env.GITHUB_EVENT_PATH }}'
                  printf 'GITHUB_GRAPHQL_URL:        %s\n'  '${{ env.GITHUB_GRAPHQL_URL }}'
                  printf 'GITHUB_HEAD_REF:           %s\n'  '${{ env.GITHUB_HEAD_REF }}'
                  printf 'GITHUB_JOB:                %s\n'  '${{ env.GITHUB_JOB }}'
                  printf 'GITHUB_PATH:               %s\n'  '${{ env.GITHUB_PATH }}'
                  printf 'GITHUB_REF:                %s\n'  '${{ env.GITHUB_REF }}'
                  printf 'GITHUB_REF_NAME:           %s\n'  '${{ env.GITHUB_REF_NAME }}'
                  printf 'GITHUB_REF_PROTECTED:      %s\n'  '${{ env.GITHUB_REF_PROTECTED }}'
                  printf 'GITHUB_REF_TYPE:           %s\n'  '${{ env.GITHUB_REF_TYPE }}'
                  printf 'GITHUB_REPOSITORY:         %s\n'  '${{ env.GITHUB_REPOSITORY }}'
                  printf 'GITHUB_REPOSITORY_OWNER:   %s\n'  '${{ env.GITHUB_REPOSITORY_OWNER }}'
                  printf 'GITHUB_RETENTION_DAYS:     %s\n'  '${{ env.GITHUB_RETENTION_DAYS }}'
                  printf 'GITHUB_RUN_ATTEMPT:        %s\n'  '${{ env.GITHUB_RUN_ATTEMPT }}'
                  printf 'GITHUB_RUN_ID:             %s\n'  '${{ env.GITHUB_RUN_ID }}'
                  printf 'GITHUB_RUN_NUMBER:         %s\n'  '${{ env.GITHUB_RUN_NUMBER }}'
                  printf 'GITHUB_SERVER_URL:         %s\n'  '${{ env.GITHUB_SERVER_URL }}'
                  printf 'GITHUB_SHA:                %s\n'  '${{ env.GITHUB_SHA }}'
                  printf 'GITHUB_STEP_SUMMARY:       %s\n'  '${{ env.GITHUB_STEP_SUMMARY }}'
                  printf 'GITHUB_WORKFLOW:           %s\n'  '${{ env.GITHUB_WORKFLOW }}'
                  printf 'GITHUB_WORKSPACE:          %s\n'  '${{ env.GITHUB_WORKSPACE }}'
                  printf 'RUNNER_ARCH:               %s\n'  '${{ env.RUNNER_ARCH }}'
                  printf 'RUNNER_DEBUG:              %s\n'  '${{ env.RUNNER_DEBUG }}'
                  printf 'RUNNER_NAME:               %s\n'  '${{ env.RUNNER_NAME }}'
                  printf 'RUNNER_OS:                 %s\n'  '${{ env.RUNNER_OS }}'
                  printf 'RUNNER_TEMP:               %s\n'  '${{ env.RUNNER_TEMP }}'
                  printf 'RUNNER_TOOL_CACHE:         %s\n'  '${{ env.RUNNER_TOOL_CACHE }}'


            - name: Report coverage
              shell: sh
              if: false
              env:
                  COVERALLS_SERVICE_NAME:   github
                  COVERALLS_GIT_COMMIT:     ${{ env.GITHUB_SHA }}
                  COVERALLS_GIT_BRANCH:     ${{ env.GITHUB_REF }}
                  COVERALLS_REPO_TOKEN:     ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: |
                  npx c8 report --reporter text-lcov | npx coveralls
