name: CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    test:
        name: Run tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name:  Install dependencies
              shell: sh
              run:   make -B install

            - name:  Run package tests
              shell: sh
              run:   make all && make coverage
