name: Atom CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    test:
        name: Run tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                channel: [stable]
        steps:
            - uses:  actions/checkout@v2
            
            - name:  Run package tests (Windows)
              if:    ${{ startsWith(matrix.os, 'Windows') }}
              run: |
                  Add-Type -AssemblyName System.Windows.Forms
                  [void] [Reflection.Assembly]::LoadWithPartialName("System.Drawing")
                  [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")
                  [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
                  [System.Windows.Forms.Screen]::AllScreens
                  (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
              shell: powershell
              env:
                  ATOM_CHANNEL: ${{ matrix.channel }}

            - name:  Upload artefacts
              uses:  actions/upload-artifact@v2
              if:    always()
              with:
                  name: screenshots.${{ matrix.os }}.${{ matrix.channel }}
                  path: .atom-mocha
                  if-no-files-found: ignore
                  retention-days: 30
