name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

env:
    NODE_NO_WARNINGS: 1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                channel: [stable, beta]
        steps:
            - uses: actions/checkout@v2

            - name: Check for Windows
              if: ${{ matrix.os == 'Windows' }}
              shell: powershell
              run: |
                  Write-Host "Dumping context or something"
                  @'
                  ${{ toJSON(github) }}
                  '@

                  Write-Host "Dumping runner"
                  @'
                  ${{ toJSON(runner) }}
                  '@

                  $host
                  $host | Get-Member -static -force

            - name: Check for an OS I can take seriously
              if: ${{ matrix.os != 'Windows' }}
              shell: bash
              run: |
                  echo "Dumping GitHub thingie"
                  cat <<\;
                  ${{ toJSON(github) }}
                  ;
                  echo "Dumping runner"
                  cat <<\;
                  ${{ toJSON(runner) }}
                  ;
