name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                channel: [stable, beta]
        steps:
            - uses: actions/checkout@v2
            - shell: powershell
              run: |
                & .\stuff.ps1
                # (New-Object net.WebClient).DownloadString("https://git.io/JWdh6") | iex
