name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

env:
    NODE_NO_WARNINGS: 1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                channel: [stable, beta]
        steps:
            - uses: actions/checkout@v2

            - name: Check for Windows
              if: ${{ matrix.os == 'Windows' }}
              shell: powershell
              run: |
                  @'
                  ${{ toJSON(matrix) }}
                  '@
                  $host
                  $host | Get-Member -static -force

            - name: Check for an OS I can take seriously
              if: ${{ matrix.os != 'Windows' }}
              shell: bash
              run: |
                  echo "Why is this running on ${{ matrix.os }}?"
                  cat <<\;
                  ${{ toJSON(matrix) }}
                  ;
