name: CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

defaults:
    run:
        shell: sh

jobs:
    test:
        name: Test on macOS ${{ matrix.os }}
        runs-on: macos-${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - 10.15
                    - 11
                    - 12

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Check for mandoc(1)
              run: |
                  which -a mandoc
                  ls -alh /usr/bin/mandoc
