name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

env:
    NODE_NO_WARNINGS: 1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                channel: [stable, beta]
        steps:
            - uses: actions/checkout@v2

            - name: A:\TAKE.EXE /A MASSI~1 /DUMP
              if: ${{ matrix.os == 'Windows' }}
              shell: powershell
              run: |
                  "github"
                  @'
                  ${{ toJSON(github) }}
                  '@
                  "env"
                  @'
                  ${{ toJSON(env) }}
                  '@
                  "job"
                  @'
                  ${{ toJSON(job) }}
                  '@
                  "steps"
                  @'
                  ${{ toJSON(steps) }}
                  '@
                  "runner"
                  @'
                  ${{ toJSON(runner) }}
                  '@
                  "needs"
                  @'
                  ${{ toJSON(needs) }}
                  '@

            - name: ./take/a/massive --dump
              if: ${{ matrix.os != 'Windows' }}
              shell: bash
              run: |
                  echo "github"
                  cat <<\;
                  ${{ toJSON(github) }}
                  ;
                  echo "env"
                  cat <<\;
                  ${{ toJSON(env) }}
                  ;
                  echo "job"
                  cat <<\;
                  ${{ toJSON(job) }}
                  ;
                  echo "steps"
                  cat <<\;
                  ${{ toJSON(steps) }}
                  ;
                  echo "runner"
                  cat <<\;
                  ${{ toJSON(runner) }}
                  ;
                  echo "needs"
                  cat <<\;
                  ${{ toJSON(needs) }}
                  ;
