name: CI

on:
    push:         {branches: [master, ci]}
    pull_request: {branches: [master, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    test:
        name: Test Node v${{ matrix.node }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node: [13.2, 14, 16, 18]

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name:  Install POSIX utilities
              if:    ${{ startsWith(matrix.os, 'Windows') }}
              shell: powershell
              run:   choco install gow

            - name:  Run package tests
              shell: sh
              run: |
                  node --version
                  npm --version
                  make all
                  make coverage
