name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest]
                channel: [v1.38.2]
        steps:
            - uses: actions/checkout@v2
            - name: Run package tests
              run: sh < ./run-ci.sh
              env:
                  ATOM_CHANNEL: ${{ matrix.channel }}
