name: Atom CI

on:
    push:         {branches: [master, main, ci]}
    pull_request: {branches: [master, main, ci]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

env:
    NODE_NO_WARNINGS: 1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                channel: [stable, beta]
        steps:
            - uses: actions/checkout@v2

            - name: Take a dump
              run: |
                echo "Dumping context or something"
                cat <<\;
                ${{ toJSON(github) }}
                ;
                echo "Dumping runner"
                cat <<\;
                ${{ toJSON(runner) }}
                ;

            - name: Check for Windows
              if: ${{ matrix.os == 'Windows' }}
              run: |
                  echo "lmao"

            - name: Check for an OS I can take seriously
              if: ${{ matrix.os != 'Windows' }}
              run: |
                  echo "NOW we're talking."
