name: Atom-CI

on:
    push:         {branches: [master]}
    pull_request: {branches: [master]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - macos-latest
                channel:
                    - stable
        steps:
            - uses: actions/checkout@v2
            
            - name: Run some stupid bullshit
              run: . ./run-ci.sh
              shell: sh
              env:
                  CHANNEL_NAME: ${{ matrix.channel }}
