name: Atom-CI

on:
    push:         {branches: [master, quick-tests]}
    pull_request: {branches: [master, quick-tests]}
    workflow_dispatch:
        # Enable manual execution via Actions tab

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Check existence of default settings
              run: . ./run-ci.sh
              shell: sh
